config/routes.rb
Rails.application.routes.draw do


  get 'hello_world', to: 'hello_world#index'
  get '/users/:id', to: 'users#show', as: 'user_path'
  get '/signup' => 'users#new'
  get '/users/edit/:id', to: 'users#edit', as: 'edit_user_path'
  patch '/users/update/:id', to: 'users#update', as: 'update_user_path'
  post '/signup' => 'users#create'

  get '/yards/show/:id', to: 'yards#show', as: 'yard_path'
  get '/yards/edit/:id', to: 'yards#edit', as: 'edit_yard_path'
  get '/yards/new', to: 'yards#new', as: 'new_yard_path'
  post '/yards', to: 'yards#create', as: 'create_yard_path'
  delete '/yards/destroy/:id', to: 'yards#destroy', as: 'destroy_yard_path'
  patch 'yards/update/:id', to: 'yards#update', as: 'update_yard_path'
  patch 'yards/updateRating/:id', to: 'yards#updateRating', as: 'update_rating_yard_path'
  get 'cities/:city', to: 'yards#cities', as: 'city_path'

  get '/bookings/answered', to: 'bookings#answered', as: 'answered_bookings_path'
  get '/bookings/incoming', to: 'bookings#incoming', as: 'incoming_bookings_path'
  get '/bookings/sent', to: 'bookings#sent', as: 'sent_bookings_path'
  get '/bookings/new', to: 'bookings#new', as: 'new_booking_path'
  delete '/bookings/destroy/:id', to: 'bookings#destroy', as: 'destroy_booking_path'
  patch 'bookings/update/:id', to: 'bookings#update', as: 'update_booking_path'

  post '/bookings', to: 'bookings#create', as: 'create_booking_path'

  get '/messages/new', to: 'messages#new', as: 'new_message_path'
  get '/messages/user/:id', to: 'messages#index', as: 'messages_path'
  get '/messages/thread/user/:id', to: 'messages#thread', as:'messages_thread_path'
  post '/messages', to: 'messages#create', as: 'create_message_path'
  post '/messages', to: 'messages#reply', as: 'create_message_in_thread_path'

  post '/friends/:id', to:'friends#create', as: 'create_friends_path'
  get '/myfriends/:id', to:'friends#index', as: 'my_friends_path'
  delete '/friends/delete/:id', to: 'friends#destroy', as: 'destroy_friends_path'
  patch '/friends/accept/:id', to: 'friends#accept', as: 'accept_friends_path'

  post '/comments', to: 'comments#create', as: 'create_comment_path'
  delete '/comments/destroy/:id', to: 'comments#destroy', as: 'destroy_comment_path'

  get '/' => 'pages#home'
  get '/about' => 'pages#about'
  get '/started' => 'pages#started'
  post '/signup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, :class_name => 'User'
  belongs_to :receiver, :class_name => 'User'
end

app/controllers/messages_controller.rb
class MessagesController < ActionController::Base

def new
  @curr_user = User.find_by_id(session[:user_id])
  @inbox = Message.where(receiver_id: @curr_user).where(is_read: false)
  @sender = User.find_by_id(session[:user_id])
  @receiver = User.find_by_id(params[:user_id])
  @yards = @receiver.yards
end

def create
  @curr_user = User.find_by_id(session[:user_id])
  @inbox = Message.where(receiver_id: @curr_user).where(is_read: false)
  @sender = User.find_by_id(session[:user_id])
  @message = Message.new(create_message_params)
  @message.is_read = false
  @message.sender = @sender
  if @message.save
    flash[:success]= "Message successfuly sent"
    redirect_to messages_path_url(@sender)
  else
    redirect_to :back
    flash[:error] = @message.errors.full_messages
  end
end

def index
  @curr_user = User.find_by_id(session[:user_id])
  @inbox = Message.where(receiver_id: @curr_user).where(is_read: false)
  @received_messages = Message.where(receiver_id: @curr_user.id.to_s)
  @sent_messages = Message.where(sender_id: @curr_user.id.to_s)
  @all_messages = @received_messages + @sent_messages
  @ids = []
  @unique_user = []
    @all_messages.each do |message|
      if message[:receiver_id].to_s == @curr_user.id.to_s
        if @ids.include?(message[:sender_id])
          p 'exists'
        else
        @ids.push(message[:sender_id])
        end
      else
        if @ids.include?(message[:receiver_id])
          p 'exists'
        else
        @ids.push(message[:receiver_id])
        end
      end
    end
    @ids.each do |id|
      @unique_user.push(User.find_by_id(id))
      p "USERS"+ @unique_user.length.to_s
    end
end

def thread
  @curr_user = User.find_by_id(session[:user_id])
  @inbox = Message.where(receiver_id: @curr_user).where(is_read: false)
  @other_user = User.find_by_id(params[:id])
  @all_sent = Message.where(receiver_id: @curr_user.id.to_s).where(sender_id: @other_user)
  @all_received = Message.where(receiver_id: @other_user.id.to_s).where(sender_id: @curr_user)
  @total_messages = @all_received + @all_sent
  @total_messages.each do |msg|
    @msg = Message.find_by_id(msg.id.to_s)
    @msg.is_read = true
    @msg.save
  end
  @message = Message.new
end


private

def message_params
  params.require(:user_id)
end

def create_message_params
  params.require(:message).permit(:receiver_id, :message)
end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YardSpace</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-confirmation/1.0.5/bootstrap-confirmation.js"></script>
  </head>
  <body>
    <%= render 'partials/navbar' %>
    <% flash.each do |name, msg| %>
  <div class="myAlert<% if name==" error" %> alert-danger <% elsif name==" success" %> alert-success <% else %> alert-info <% end %>">
    <%= msg %>
  </div>
  <% end %>
  <br /><br />
  <div class ="container">
<h1>Message inbox</h1>
<%@unique_user.each do |uq_user|%>
<div class ="message-thread row">
  <div class ="col-xs-4">
    <h3><%=uq_user.name%></h3>
    <%=link_to user_path_url(uq_user) do %>
    <%if uq_user.image%>
    <img class="book-prof profilePic" src="<%=uq_user.image%>" alt="profile pic">
    <%else%>
    <img class="book-prof profilePic" src="http://i.imgur.com/IulSm39.jpg" alt="profile pic">
    <%end%>
     <%end%>
  </div>
  <div class ="col-xs-4 see-msg-btn">
<h3><%= button_to 'See conversation', messages_thread_path_url(uq_user), :method => 'get', class: 'cool-btn',:style=>"color:#31493C;font-size:24px"%></h3>
  </div>
</div>
<%end%>
</div>

</div>
<%= render 'partials/footer' %>

</body>
</html>

app/views/messages/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YardSpace</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-confirmation/1.0.5/bootstrap-confirmation.js"></script>
  </head>
  <body>
    <%= render 'partials/navbar' %>
    <% flash.each do |name, msg| %>
  <div class="myAlert<% if name==" error" %> alert-danger <% elsif name==" success" %> alert-success <% else %> alert-info <% end %>">
    <%= msg %>
  </div>
  <% end %>
  <div class ="container">
<br /><br />
  <div class = "row">
    <div class = "col-xs-8 text-center">
<h1>Write a new message</h1>
<h3>TO: <%=@receiver.name%></h3>
<%= form_for(:message, :url => create_message_path_url(@message), html: {method: :post}) do |f| %>
<%= f.text_area :message, placeholder: "Write you message to "+@receiver.name+" here" , :cols => "80", :rows=>"3"%><br />
<%= f.hidden_field :receiver_id, :value => @receiver.id.to_s%>
<%= f.submit "post", :controller => 'messages'%>
</div>
<div class = "col-xs-4 text-center">
  <h1><%=@receiver.name%>'s yards</h1>
<% @yards.each do |yard|%>
<%=link_to yard_path_url(yard) do %>
<%= image_tag('http://i.imgur.com/5gkUOut.jpg')%>
<%end%>
<h3><%= yard.title%></h3>
<%= yard.description%><br/>
<%if yard.kid_and_pet_friendly%>
<p>Kid and Pet friendly!</p>
<%else%>
<p>No pets or kids sadly</p>
<%end%>
<%if yard.fire_friendly%>
<p>Campfires allowed!</p>
<%else%>
<p>No campfires</p>
<%end%>
<%= yard.city %>
<%= yard.zipcode%>
<hr />
<%end%>
</div>
<%end%>
</div>
</div>

</div>
<%= render 'partials/footer' %>

</body>
</html>

app/views/messages/thread.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YardSpace</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Latest compiled and minified CSS -->
  <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-confirmation/1.0.5/bootstrap-confirmation.js"></script>
  </head>
  <body>
    <%= render 'partials/navbar' %>
    <% flash.each do |name, msg| %>
  <div class="myAlert<% if name==" error" %> alert-danger <% elsif name==" success" %> alert-success <% else %> alert-info <% end %>">
    <%= msg %>
  </div>
  <% end %>
  <br /><br />
  <%=link_to messages_path_url(@curr_user) do %>
  <h3><span class ="glyphicon glyphicon-arrow-left"</span><span>Back2Inbox</span></h3>
  <%end%>
<h1 style ="margin-left:30px">Messages with <%=@other_user.name%></h1>
<br />
<div class ="message-box row">
<% @total_messages.each do |msg|%>
<% @sender = User.find_by_id(msg.sender_id)%>
<div class = "col-xs-2 text-center">
  <%=link_to user_path_url(@sender) do %>
  <%if @sender.image%>
  <img class="msg-pic" src="<%=@sender.image%>" alt="profile pic">
  <%else%>
  <img class="msg-pic" src="http://i.imgur.com/IulSm39.jpg" alt="profile pic">
  <%end%>
 <%end%>
    <hr />
</div>
<div class ="col-xs-10">
  <h4><%= @sender.name%>:
      <%= msg.message %></h4>
  <h6><%= msg.created_at%></h6>
  <hr />
</div>
<%end%>
</div>
<div class ="reply-msg">
<h3>Reply to: <%=@other_user.name%></h3>
<%= form_for(:message, :url => create_message_in_thread_path_url(@message), html: {method: :post}) do |f| %>
<%= f.text_area :message, placeholder: "Write you message to "+@other_user.name+" here" , :cols => "80", :rows=>"3"%><br />
<%= f.hidden_field :receiver_id, :value => @other_user.id.to_s%>
<%= f.submit "post", :controller => 'messages'%>
<%end%>
</div>
<%= render 'partials/footer' %>

</body>
</html>