config/routes.rb
Rails.application.routes.draw do


  get 'hello_world', to: 'hello_world#index'
  get '/users/:id', to: 'users#show', as: 'user_path'
  get '/signup' => 'users#new'
  get '/users/edit/:id', to: 'users#edit', as: 'edit_user_path'
  patch '/users/update/:id', to: 'users#update', as: 'update_user_path'
  post '/signup' => 'users#create'

  get '/yards/show/:id', to: 'yards#show', as: 'yard_path'
  get '/yards/edit/:id', to: 'yards#edit', as: 'edit_yard_path'
  get '/yards/new', to: 'yards#new', as: 'new_yard_path'
  post '/yards', to: 'yards#create', as: 'create_yard_path'
  delete '/yards/destroy/:id', to: 'yards#destroy', as: 'destroy_yard_path'
  patch 'yards/update/:id', to: 'yards#update', as: 'update_yard_path'
  patch 'yards/updateRating/:id', to: 'yards#updateRating', as: 'update_rating_yard_path'
  get 'cities/:city', to: 'yards#cities', as: 'city_path'

  get '/bookings/answered', to: 'bookings#answered', as: 'answered_bookings_path'
  get '/bookings/incoming', to: 'bookings#incoming', as: 'incoming_bookings_path'
  get '/bookings/sent', to: 'bookings#sent', as: 'sent_bookings_path'
  get '/bookings/new', to: 'bookings#new', as: 'new_booking_path'
  delete '/bookings/destroy/:id', to: 'bookings#destroy', as: 'destroy_booking_path'
  patch 'bookings/update/:id', to: 'bookings#update', as: 'update_booking_path'

  post '/bookings', to: 'bookings#create', as: 'create_booking_path'

  get '/messages/new', to: 'messages#new', as: 'new_message_path'
  get '/messages/user/:id', to: 'messages#index', as: 'messages_path'
  get '/messages/thread/user/:id', to: 'messages#thread', as:'messages_thread_path'
  post '/messages', to: 'messages#create', as: 'create_message_path'
  post '/messages', to: 'messages#reply', as: 'create_message_in_thread_path'

  post '/friends/:id', to:'friends#create', as: 'create_friends_path'
  get '/myfriends/:id', to:'friends#index', as: 'my_friends_path'
  delete '/friends/delete/:id', to: 'friends#destroy', as: 'destroy_friends_path'
  patch '/friends/accept/:id', to: 'friends#accept', as: 'accept_friends_path'

  post '/comments', to: 'comments#create', as: 'create_comment_path'
  delete '/comments/destroy/:id', to: 'comments#destroy', as: 'destroy_comment_path'

  get '/' => 'pages#home'
  get '/about' => 'pages#about'
  get '/started' => 'pages#started'
  post '/signup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
end

app/models/yard.rb
class Yard < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :bookings

  enum city: [:sf_bay_area, :santa_cruz, :lake_tahoe, :yosemite, :santa_barbara, :sonoma, :los_angeles]
end

app/controllers/yards_controller.rb
class YardsController < ApplicationController
  require 'httparty'
  include HTTParty

def new
  @yard = Yard.new
  @curr_user = User.find_by_id(current_user.id.to_s)
  @inbox = Message.where(receiver_id: @curr_user).where(is_read: false)
end


def create
  @curr_user = User.find_by_id(current_user.id.to_s)
  @inbox = Message.where(receiver_id: @curr_user).where(is_read: false)
  @yard = Yard.new()
  @yard.title = yard_params[:title]
  @yard.description = yard_params[:description]
  @yard.city = yard_params[:city].to_i
  @yard.zipcode = yard_params[:zipcode]
  @yard.kid_and_pet_friendly = yard_params[:kid_and_pet_friendly]
  @yard.fire_friendly = yard_params[:fire_friendly]
  @yard.image = yard_params[:image]
  @yard.rating = 0
  @yard.r_count = 0
  @yard.user = @curr_user
  if @yard.save
    redirect_to user_path_url(@curr_user)
  else
    flash[:error] = @yard.errors.full_messages.join(", ")
    redirect_to :back
  end
end

def show
  if(logged_in?)
  @comment = Comment.new()
  @curr_user = User.find_by_id(current_user.id.to_s)
  @inbox = Message.where(receiver_id: @curr_user).where(is_read: false)
  end
  @yard = Yard.find_by_id(params[:id])
  @comments = Comment.where(yard_id: @yard.id.to_s)
end

def destroy
  @yard = Yard.find_by_id(params[:id])
  @bookings = Booking.where(yard_id: @yard.id.to_s)
  @bookings.delete_all
  if @yard.destroy
    flash[:error] = @yard.title + 'was deleted, never to be seen again..'
    redirect_to :back
  else
    flash[:error] = "try deleting again, something went wrong"
  end
end

def edit
  @curr_user = User.find_by_id(current_user.id.to_s)
  @inbox = Message.where(receiver_id: @curr_user).where(is_read: false)
  @yard = Yard.find_by_id(params[:id])
end

def update
  @curr_user = User.find_by_id(current_user.id.to_s)
  @inbox = Message.where(receiver_id: @curr_user).where(is_read: false)
  @yard = Yard.find_by_id(params[:id])
  if @yard.update(yard_params)
    redirect_to user_path_url(@curr_user)
  else
    flash[:error] = @yard.errors.full_messages
    redirect_to :back
  end
end

def updateRating
  @curr_user = User.find_by_id(current_user.id.to_s)
  @inbox = Message.where(receiver_id: @curr_user).where(is_read: false)
  @yard = Yard.find_by_id(params[:id])
  @yard.r_count += 1
  @yard.rating += yard_rating_params[:rating].to_i
  @yard.save
  cookies[:rated] = '.' if cookies[:rated].nil?
  cookies[:rated] += @yard.id.to_s + '.'
  redirect_to :back
end

def cities
  @curr_user = User.find_by_id(session[:user_id]) if session[:user_id]
  @inbox = Message.where(receiver_id: @curr_user).where(is_read: false)
  @yards = Yard.where(city: params[:city])
  @city = params[:city]
  weather_hash = fetch_weather params[:city]
  assign_values(weather_hash)
end

private

def yard_params
  params.require(:yard).permit(:title, :description, :kid_and_pet_friendly, :fire_friendly, :zipcode, :city, :image)
end

def yard_rating_params
  params.require(:yard).permit(:rating)
end


attr_accessor :temperature, :icon
def initialize

end

def fetch_weather city
  puts city
    if city == 'sf_bay_area'
      zipcode = 94107
    elsif city == 'santa_cruz'
      zipcode = 95060
    elsif city == 'lake_tahoe'
      zipcode = 96150
    elsif city == 'yosemite'
      zipcode = 95389
    elsif city == 'santa_barbara'
      zipcode = 93101
    elsif city == 'sonoma'
      zipcode = 95476
    elsif city == 'los_angeles'
      zipcode = 90001
    end
   @response = HTTParty.get("http://api.openweathermap.org/data/2.5/forecast/daily?zip=#{zipcode}&cnt=6&APPID=56816b6400cf26a5068b34d20251372f")
 end


  def assign_values(weather_hash)
    require 'date'
         @forecast_response = weather_hash.parsed_response['city']
         @date0 = weather_hash.parsed_response['list'][0]['dt']
         @day0_date = Time.at(@date0).to_date.strftime("%m/%d")
         @day0 = weather_hash.parsed_response['list'][0]['temp']['day']
         @day0_temp = ((1.8*(@day0-273))+32).floor
         @night0 = weather_hash.parsed_response['list'][0]['temp']['night']
         @night0_temp = ((1.8*(@night0-273))+32).floor
         @day0_icon = weather_hash.parsed_response['list'][0]['weather'][0]['icon']
         @day0_des = weather_hash.parsed_response['list'][0]['weather'][0]['description']

         @date1 = weather_hash.parsed_response['list'][1]['dt']
         @day1_date = Time.at(@date1).to_date.strftime("%m/%d")
         @day1 = weather_hash.parsed_response['list'][1]['temp']['day']
         @day1_temp = ((1.8*(@day1-273))+32).floor
         @night1 = weather_hash.parsed_response['list'][1]['temp']['night']
         @night1_temp = ((1.8*(@night1-273))+32).floor
         @day1_icon = weather_hash.parsed_response['list'][1]['weather'][0]['icon']
         @day1_des = weather_hash.parsed_response['list'][1]['weather'][0]['description']

         @date2 = weather_hash.parsed_response['list'][2]['dt']
         @day2_date = Time.at(@date2).to_date.strftime("%m/%d")
         @day2 = weather_hash.parsed_response['list'][2]['temp']['day']
         @day2_temp = ((1.8*(@day2-273))+32).floor
         @night2 = weather_hash.parsed_response['list'][2]['temp']['night']
         @night2_temp = ((1.8*(@night2-273))+32).floor
         @day2_icon = weather_hash.parsed_response['list'][2]['weather'][0]['icon']
         @day2_des = weather_hash.parsed_response['list'][2]['weather'][0]['description']

         @date3 = weather_hash.parsed_response['list'][3]['dt']
         @day3_date = Time.at(@date3).to_date.strftime("%m/%d")
         @day3 = weather_hash.parsed_response['list'][3]['temp']['day']
         @day3_temp = ((1.8*(@day3-273))+32).floor
         @night3 = weather_hash.parsed_response['list'][3]['temp']['night']
         @night3_temp = ((1.8*(@night3-273))+32).floor
         @day3_icon = weather_hash.parsed_response['list'][3]['weather'][0]['icon']
         @day3_des = weather_hash.parsed_response['list'][3]['weather'][0]['description']

         @date4 = weather_hash.parsed_response['list'][4]['dt']
         @day4_date = Time.at(@date4).to_date.strftime("%m/%d")
         @day4 = weather_hash.parsed_response['list'][4]['temp']['day']
         @day4_temp = ((1.8*(@day4-273))+32).floor
         @night4 = weather_hash.parsed_response['list'][4]['temp']['night']
         @night4_temp = ((1.8*(@night4-273))+32).floor
         @day4_icon = weather_hash.parsed_response['list'][4]['weather'][0]['icon']
         @day4_des = weather_hash.parsed_response['list'][4]['weather'][0]['description']

         @date5 = weather_hash.parsed_response['list'][5]['dt']
         @day5_date = Time.at(@date5).to_date.strftime("%m/%d")
         @day5 = weather_hash.parsed_response['list'][5]['temp']['day']
         @day5_temp = ((1.8*(@day5-273))+32).floor
         @night5 = weather_hash.parsed_response['list'][5]['temp']['night']
         @night5_temp = ((1.8*(@night5-273))+32).floor
         @day5_icon = weather_hash.parsed_response['list'][5]['weather'][0]['icon']
         @day5_des = weather_hash.parsed_response['list'][5]['weather'][0]['description']

   end

end

app/helpers/yards_helper.rb
module YardsHelper
end

app/views/yards/cities.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YardSpace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-confirmation/1.0.5/bootstrap-confirmation.js"></script>
  </head>
  <body>
    <%= render 'partials/navbar' %>
    <br/><br />
    <h1 class="text-center"><%= @city%></h1>
    <div class="row text-center weather">
      <div class="col-xs-2">
        <%= @day0_date%><br/>
        <%=image_tag('http://openweathermap.org/img/w/'+@day0_icon+'.png')%><br/>
        <%= @day0_des%>
        <p>Day:
          <%= @day0_temp%>
          F</p>
        <p>Night:
          <%= @night0_temp%>
          F</p>
      </div>
      <div class="col-xs-2">
        <%= @day1_date%><br/>
        <%=image_tag('http://openweathermap.org/img/w/'+@day1_icon+'.png')%><br/>
        <%= @day1_des%>
        <p>Day:
          <%= @day1_temp%>
          F</p>
        <p>Night:
          <%= @night1_temp%>
          F</p>
      </div>
      <div class="col-xs-2">
        <%= @day2_date%><br/>
        <%=image_tag('http://openweathermap.org/img/w/'+@day2_icon+'.png')%><br/>
        <%= @day2_des%>
        <p>Day:
          <%= @day2_temp%>
          F</p>
        <p>Night:
          <%= @night2_temp%>
          F</p>
      </div>
      <div class="col-xs-2">
        <%= @day3_date%><br/>
        <%=image_tag('http://openweathermap.org/img/w/'+@day3_icon+'.png')%><br/>
        <%= @day3_des%>
        <p>Day:
          <%= @day3_temp%>
          F</p>
        <p>Night:
          <%= @night3_temp%>
          F</p>
      </div>
      <div class="col-xs-2">
        <%= @day4_date%><br/>
        <%=image_tag('http://openweathermap.org/img/w/'+@day4_icon+'.png')%><br/>
        <%= @day4_des%>
        <p>Day:
          <%= @day4_temp%>
          F</p>
        <p>Night:
          <%= @night4_temp%>
          F</p>
      </div>
      <div class="col-xs-2">
        <%= @day5_date%><br/>
        <%=image_tag('http://openweathermap.org/img/w/'+@day5_icon+'.png')%><br/>
        <%= @day5_des%>
        <p>Day:
          <%= @day5_temp%>
          F</p>
        <p>Night:
          <%= @night5_temp%>
          F</p>
      </div>
    </div>
    <div class="container city-back-color">

        <%if @yards.present?%>
        <%@yards.each do |yard|%>
        <div class="row yard-city">
          <%if yard.user.is_hosting == true%>
          <div class="col-xs-3 yard-city-details">
            <%if yard.rating > 0 %>
            <h2 class ="peakaboo">Rating:
              <%=yard.rating / yard.r_count%>/10</h2>
              <%else%>
              <h2 class ="peakaboo">No ratings yet</h2>
              <%end%>
              <%if yard.kid_and_pet_friendly%>
              <h2 class="text-left peakaboo">Kid and Pet friendly!</h2>
              <%else%>
              <h2 class="text-left peakaboo">No pets or kids sadly</h2>
              <%end%>
              <h3 class="text-left peakaboo"><%= yard.zipcode%></h3>
              <%if yard.fire_friendly%>
              <h2 class="text-left">
                <span class="glyphicon glyphicon-fire peakaboo"></span>
                <span  class ="peakaboo">
                  Campfires ok</span>
                </h2><br/>
                <%end%>
              </div>
          <div class="col-xs-4 ">
            <h1><%= yard.title%></h1>
            <%=link_to yard_path_url(yard) do %>
            <%if yard.image%>
            <img class="city-pic" src='<%=yard.image%>' alt="profile pic">
            <%else%>
                <img class="city-pic" src="http://i.imgur.com/5gkUOut.jpg" alt="profile pic">
              <%end%>
            <%end%>
          </div>
          <div class="col-xs-5 user-city text-center">
            <%=link_to user_path_url(yard.user) do %>
            <%if yard.user.image%>
            <img class="profCity profilePic" src="<%=yard.user.image%>" alt="profile pic">
            <%else%>
            <img class="profCity profilePic" src="http://i.imgur.com/IulSm39.jpg" alt="profile pic">
            <%end%>            <%end%>
            <h2 class="text-center"><%=yard.user.name%>--
            <%= yard.user.yards.count%> more yards available</h2>
          <%end%>
        </div>
      </div>
      <hr/>
        <%end%>

        <%end%>
      </div>
    <%= render 'partials/footer' %>

  </body>
</html>

app/views/yards/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YardSpace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-confirmation/1.0.5/bootstrap-confirmation.js"></script>
  </head>
  <body>
    <%= render 'partials/navbar' %>

<h1 align="center">Edit your yard!</h1>
<%= form_for @yard, html: { multipart: true }, :url => update_yard_path_url(@yard) do |f| %>
<div class="container form-group">
    <div class="col align-self-center">
          <h3>Your tent is locked in <%= @yard.city%></h3>
      <%= f.label :title, 'Title' %><br>
      <%= f.text_field :title, class: "form-control", placeholder: "quick title for yard" %>
      <br/>
      <%= f.label :description, 'Description' %><br>
      <%= f.text_area :description, placeholder: "tell people how great your yard is", class: "form-control" %>
      <br/>
      <%= f.label :zipcode, 'Provide zipcode for better accuracy' %><br>
      <%= f.number_field :zipcode, class: "form-control" %>
      <br/>
      <%= f.label :kid_and_pet_friendly, 'Kids and Pets ok?' %><br>
      <%= f.check_box :kid_and_pet_friendly, class: "form-control" %>
      <br/>
      <%= f.label :fire_friendly, 'What about campfires?' %><br>
      <%= f.check_box :fire_friendly, class: "form-control" %>
      <br/>
      <%= f.submit "Save Changes", class: 'btn btn-success btn-md center-block', align:"right" %>
      <%end%>
    </div>
</div>
<%= render 'partials/footer' %>

</body>
</html>

app/views/yards/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YardSpace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-confirmation/1.0.5/bootstrap-confirmation.js"></script>
  </head>
  <body>
    <%= render 'partials/navbar' %>

<h1 align="center">Create a new trade yard!</h1>

<br>

<div class="container" >
  <div class="col-md-12">
    <%= form_for Yard.new, :url => create_yard_path_url(@yard)  do |f|%>
      <div class="container" >
        <div class="form-group" id="newYardForm">

          <%= f.label :title, 'Title' %><br>
          <%= f.text_field :title, class: "form-control", placeholder: "quick title for yard" %>
          <br/>
          <%= f.label :description, 'Description' %><br>
          <%= f.text_area :description, placeholder: "tell people how great your yard is", class: "form-control" %>
          <br/>
          <label>Select a city</label>
          <select id="cityDropdown" class="form-control" name="yard[city]">
            <option value=-1></option>
            <option value=0>Sf-Bay Area</option>
            <option value=1>Santa Cruz</option>
            <option value=2>Lake Tahoe</option>
            <option value=3>Yosemite</option>
            <option value=4>Santa Barbara</option>
            <option value=5>Sonoma</option>
            <option value=6>Los Angeles</option>
          </select>
          <%= f.label :zipcode, 'Provide zipcode for better accuracy' %><br>
          <%= f.number_field :zipcode, class: "form-control" %>
          <br/>
          <%= f.label :image, 'Attach IMG url here' %><br>
          <%= f.text_area :image, class: "form-control", placeholder: 'You can also upload an image onto imgur.com and then copy the link here' %>
          <br />
          <%= f.label :kid_and_pet_friendly, 'Kids and Pets ok?' %><br>
          <%= f.check_box :kid_and_pet_friendly, class: "form-control" %>
          <br/>
          <%= f.label :fire_friendly, 'What about campfires?' %><br>
          <%= f.check_box :fire_friendly, class: "form-control" %>
          <br/>
          <%= f.submit "Add yard", class: 'btn btn-primary btn-md center-block', align:"right" %>
        </div>
      </div>
    <% end %>

  </div>
</div>
<%= render 'partials/footer' %>

</body>
</html>

app/views/yards/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YardSpace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-confirmation/1.0.5/bootstrap-confirmation.js"></script>
  </head>
  <body>
    <%= render 'partials/navbar' %>
    <br /><br /><br />
    <%if @yard.r_count == 0%>
    <%@stars = @yard.rating / 1%>
    <%else%>
    <%@stars = @yard.rating / @yard.r_count%>
    <%end%>
        <div class="container">
          <div class="row"style="background-color:#86A397;border-radius:20px">
            <h1 style="margin-left:120px"><%=@yard.title%>--<%=@yard.city%> <span style="font-size:22px"> <%= @stars %>/10 rating</span></h1>
            <div class="col-xs-6 text-right">
              <%if logged_in? && @curr_user.id == current_user.id%>
              <% @check = false %>
              <%if cookies[:rated]%>
              <% @rated = cookies[:rated].split('.')%>
              <% @rated.each do |id|%>
              <%if id == @yard.id.to_s%>
              <% @check = true %>
              <%end%>
              <%end%>
              <%end%>
              <%if @check == false%>
              <%= form_for @yard, :class => 'form-group', :url => update_rating_yard_path_url(@yard) do |f| %>
              <%= f.label :rating %>
              <%= f.number_field :rating, :value => 0, :max => 10, :min => 1, :class=>"mx-sm-3" %>
              <%= f.submit "Rate", :class => "text-muted btn-primary btn-xs" %>
              <% end %>
              <%end%>
              <%end%>
              <%if @yard.image%>
              <img class="show-yard-pic text-center" src='<%=@yard.image%>' alt="profile pic">
              <%else%>
                  <img class="show-yard-pic text-center" src="http://i.imgur.com/5gkUOut.jpg" alt="profile pic">
                <%end%>
            </div>
            <div class="col-xs-4 yard-info">
              <div class ="row">
                <div class ="col-xs-6">
                  <h1><%= @yard.user.name%></h1>
                  <h2><%= @yard.user.yards.count.to_i - 1%> more available yards</h2>
                  <%=link_to user_path_url(@yard.user) do %>
                  <%if @yard.user.image%>
                  <img class="small-profilePic" src="<%=@yard.user.image%>" alt="profile pic">
                  <%else%>
                  <img class="small-profilePic" src="http://i.imgur.com/IulSm39.jpg" alt="profile pic">
                  <%end%>
                  <%end%>
                </div>
                <div class ="col-xs-6">
                  <% if (logged_in? && @curr_user.id.to_s != @yard.user.id.to_s)%>
                  <%= link_to new_message_path_url(:user_id => @yard.user.id) do%>
                  <h2 class ="text-left"><span class = "glyphicon glyphicon-envelope"style="color:#31493C"></span></h2>
                  <%end%>
                  <%end%>
                </div>
            </div>
              <h2><%= @yard.description%></h2>
                <%if @yard.kid_and_pet_friendly%>
                <h3>Kid and Pet friendly!</h3>
                <%else%>
                <h3>No pets or kids sadly</h3>
                <%end%>
                <%if @yard.fire_friendly%>
                <h3><span class = "glyphicon glyphicon-fire"></span><span>fire friendly</span></h3>
                <%end%>
              <% if (logged_in? && @curr_user.id.to_s != @yard.user.id.to_s)%>
              <%= link_to new_booking_path_url(yard_id: @yard.id), :controller => 'bookings', :method => 'get', :class=>'cool-btn' do %>
                <h2><span class ="glyphicon glyphicon-tent book-btn"style="color:#86A397"></span><span class ="book-btn"style="color:#86A397">Camp Here!</span></h2>
                <%end%>
                <%else%>
                <h3 style ="color:red">Creat an account to book here</h3>
              <%end%>
            </div>
            <div class="col-xs-3 prof-yard-show">
            </div>
          </div>
          <div class="row">
            <br />
            <h1 class="text-center">Reviews</h1>
            <% if logged_in?%>
            <div class="add-comment-box text-center">
              <%= form_for(:comment, :url => create_comment_path_url(@comment), html: {method: :post}) do |f| %>
              <%= f.text_area :title, placeholder: "title", :cols => "50", :rows=>"1"%><br/>
              <%= f.text_area :body, placeholder: "write a review about "+ @yard.title, :cols => "80", :rows=>"2"%>
              <%= f.hidden_field :yard_id, :value => @yard.id.to_s%>
              <%= f.submit "post", :controller => 'comments', :class => 'cool-btn' ,:style=>"color:#31493C"%>
            </div>
            <br />
            <%end%>
          <% else %>
            <h3>sign up to join in the commenting fun</h3>
            <%end%>
            <div class="comment-box">
              <%@comments.each do |comment| %>
              <h2><%= comment.title%></h2>
              <h3><%= comment.body%> -- <%= comment.user.name%>
              <% if (logged_in? && @curr_user.id.to_s == comment.user.id.to_s)%>
              <%= link_to destroy_comment_path_url(comment), :method=>'delete' do %>
              <span class="glyphicon glyphicon-remove" style="color:red"></span></h3>
              <%end%>
              <%end%>
              <hr />
              <%end%>
            </div>
          </div>
        </div>
        <%= render 'partials/footer' %>

      </body>
    </html>