config/routes.rb
Rails.application.routes.draw do


  get 'hello_world', to: 'hello_world#index'
  get '/users/:id', to: 'users#show', as: 'user_path'
  get '/signup' => 'users#new'
  get '/users/edit/:id', to: 'users#edit', as: 'edit_user_path'
  patch '/users/update/:id', to: 'users#update', as: 'update_user_path'
  post '/signup' => 'users#create'

  get '/yards/show/:id', to: 'yards#show', as: 'yard_path'
  get '/yards/edit/:id', to: 'yards#edit', as: 'edit_yard_path'
  get '/yards/new', to: 'yards#new', as: 'new_yard_path'
  post '/yards', to: 'yards#create', as: 'create_yard_path'
  delete '/yards/destroy/:id', to: 'yards#destroy', as: 'destroy_yard_path'
  patch 'yards/update/:id', to: 'yards#update', as: 'update_yard_path'
  patch 'yards/updateRating/:id', to: 'yards#updateRating', as: 'update_rating_yard_path'
  get 'cities/:city', to: 'yards#cities', as: 'city_path'

  get '/bookings/answered', to: 'bookings#answered', as: 'answered_bookings_path'
  get '/bookings/incoming', to: 'bookings#incoming', as: 'incoming_bookings_path'
  get '/bookings/sent', to: 'bookings#sent', as: 'sent_bookings_path'
  get '/bookings/new', to: 'bookings#new', as: 'new_booking_path'
  delete '/bookings/destroy/:id', to: 'bookings#destroy', as: 'destroy_booking_path'
  patch 'bookings/update/:id', to: 'bookings#update', as: 'update_booking_path'

  post '/bookings', to: 'bookings#create', as: 'create_booking_path'

  get '/messages/new', to: 'messages#new', as: 'new_message_path'
  get '/messages/user/:id', to: 'messages#index', as: 'messages_path'
  get '/messages/thread/user/:id', to: 'messages#thread', as:'messages_thread_path'
  post '/messages', to: 'messages#create', as: 'create_message_path'
  post '/messages', to: 'messages#reply', as: 'create_message_in_thread_path'

  post '/friends/:id', to:'friends#create', as: 'create_friends_path'
  get '/myfriends/:id', to:'friends#index', as: 'my_friends_path'
  delete '/friends/delete/:id', to: 'friends#destroy', as: 'destroy_friends_path'
  patch '/friends/accept/:id', to: 'friends#accept', as: 'accept_friends_path'

  post '/comments', to: 'comments#create', as: 'create_comment_path'
  delete '/comments/destroy/:id', to: 'comments#destroy', as: 'destroy_comment_path'

  get '/' => 'pages#home'
  get '/about' => 'pages#about'
  get '/started' => 'pages#started'
  post '/signup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
end

app/views/partials/_footer.html.erb
<div class="panel container-fluid">
<div class="panel-footer text-center row">
<p>info@yardspace.com-Jesse Rosenbloom (510) 590-8368 </p>
</div>
</div>

app/views/partials/_navbar.html.erb
<nav id="mainNav" class=" nav navbar-default navbar-fixed-top topnav" role="navigation">
  <div class="row" >
    <div class ="col-xs-1">
    <ul class="nav_padding_right">
      <p class ="text-center"><%= link_to '/' do %>
      <span class ="glyphicon glyphicon-tent"></span></p>
      <%end%>
    </div>
    <div class ="col-xs-2 text-center">
      <%= link_to 'About YS', '/about'%>
    </div>
    <div class ="col-xs-3 pull-left">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cities <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li style='font-size:20px'><%=link_to 'SF-Bay Area', '/cities/sf_bay_area', controller: "yards"%></li>
          <li style='font-size:20px'><%=link_to 'Santa Cruz', '/cities/santa_cruz', controller: "yards"%></li>
          <li style='font-size:20px'><%=link_to 'Lake Tahoe', '/cities/lake_tahoe', controller: "yards"%></li>
          <li style='font-size:20px'><%=link_to 'Yosemite', '/cities/yosemite', controller: "yards"%></li>
          <li style='font-size:20px'><%=link_to 'Santa Barbara', '/cities/santa_barbara', controller: "yards"%></li>
          <li style='font-size:20px'><%=link_to 'Sonoma', '/cities/sonoma', controller: "yards"%></li>
          <li style='font-size:20px'><%=link_to 'Los Angeles', '/cities/los_angeles', controller: "yards"%></li>
        </ul>
      </li>
    </div>
    <div class ="col-xs-2">
      <% if User.find_by_id(session[:user_id]) %>
        <p class = "pull-right"><%= link_to user_path_url(User.find_by_id(session[:user_id])) do %>
        <span><%=(User.find_by_id(session[:user_id]).email)%></span><span class="cart glyphicon glyphicon-user"></span></p>
        <%end%>
        <%end%>
      </div>
      <div class ="col-xs-2">
        <% if User.find_by_id(session[:user_id]) %>
          <p class = "pull-right"><%= link_to messages_path_url(User.find_by_id(session[:user_id])) do%>
            <span>Inbox <span class="cart glyphicon glyphicon-inbox"></span>
            <%end%>
          <span style="color:red"><%=@inbox.count%></span></p>
      <%end%>
    </div>
    <div class ="col-xs-2">
      <% if User.find_by_id(session[:user_id]) %>
      <p class = "text-center"><%= link_to 'Log Out', logout_path, method: :delete%></p>
      <% else %>
      <p class ="pull-center"><%= link_to 'Log In', login_path %> |
      <%= link_to 'Sign Up', signup_path %></p>
      <% end %>
    </div>
</nav>
</div>