config/routes.rb
Rails.application.routes.draw do


  get 'hello_world', to: 'hello_world#index'
  get '/users/:id', to: 'users#show', as: 'user_path'
  get '/signup' => 'users#new'
  get '/users/edit/:id', to: 'users#edit', as: 'edit_user_path'
  patch '/users/update/:id', to: 'users#update', as: 'update_user_path'
  post '/signup' => 'users#create'

  get '/yards/show/:id', to: 'yards#show', as: 'yard_path'
  get '/yards/edit/:id', to: 'yards#edit', as: 'edit_yard_path'
  get '/yards/new', to: 'yards#new', as: 'new_yard_path'
  post '/yards', to: 'yards#create', as: 'create_yard_path'
  delete '/yards/destroy/:id', to: 'yards#destroy', as: 'destroy_yard_path'
  patch 'yards/update/:id', to: 'yards#update', as: 'update_yard_path'
  patch 'yards/updateRating/:id', to: 'yards#updateRating', as: 'update_rating_yard_path'
  get 'cities/:city', to: 'yards#cities', as: 'city_path'

  get '/bookings/answered', to: 'bookings#answered', as: 'answered_bookings_path'
  get '/bookings/incoming', to: 'bookings#incoming', as: 'incoming_bookings_path'
  get '/bookings/sent', to: 'bookings#sent', as: 'sent_bookings_path'
  get '/bookings/new', to: 'bookings#new', as: 'new_booking_path'
  delete '/bookings/destroy/:id', to: 'bookings#destroy', as: 'destroy_booking_path'
  patch 'bookings/update/:id', to: 'bookings#update', as: 'update_booking_path'

  post '/bookings', to: 'bookings#create', as: 'create_booking_path'

  get '/messages/new', to: 'messages#new', as: 'new_message_path'
  get '/messages/user/:id', to: 'messages#index', as: 'messages_path'
  get '/messages/thread/user/:id', to: 'messages#thread', as:'messages_thread_path'
  post '/messages', to: 'messages#create', as: 'create_message_path'
  post '/messages', to: 'messages#reply', as: 'create_message_in_thread_path'

  post '/friends/:id', to:'friends#create', as: 'create_friends_path'
  get '/myfriends/:id', to:'friends#index', as: 'my_friends_path'
  delete '/friends/delete/:id', to: 'friends#destroy', as: 'destroy_friends_path'
  patch '/friends/accept/:id', to: 'friends#accept', as: 'accept_friends_path'

  post '/comments', to: 'comments#create', as: 'create_comment_path'
  delete '/comments/destroy/:id', to: 'comments#destroy', as: 'destroy_comment_path'

  get '/' => 'pages#home'
  get '/about' => 'pages#about'
  get '/started' => 'pages#started'
  post '/signup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
belongs_to :booking, optional: true
belongs_to :message, optional: true
belongs_to :friend, optional: true
has_many :yards
has_many :comments

has_secure_password

validates :email, presence: true,
uniqueness: { case_sensitive: false },
length: { minimum: 3, maximum: 25 }

validates :name, presence: true,
length: { minimum: 3, maximum: 25 }

validates :password, presence: true,
length: { minimum: 3, maximum: 25 }, on: :create
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @curr_user = User.new()
  end

  def create
    @curr_user = User.new(user_params_create)
    if @curr_user.save
      session[:user_id] = @curr_user.id
      redirect_to '/started'
    else
      flash[:error] = @curr_user.errors.full_messages
      render 'new'
    end
  end

  def show
    @curr_user = User.find_by_id(session[:user_id]) if session[:user_id]
    if @curr_user
    @friend = Friend.where(me_id: @curr_user.id).where(you_id: params[:id])
    @ship = Friend.where(you_id: @curr_user.id).where(me_id: params[:id])
    @friendship = @friend + @ship
  end
    @user = User.find_by_id(params[:id])
    @inbox = Message.where(receiver_id: @user).where(is_read: false)
    @yards = @user.yards
    @incoming_pending_bookings = Booking.where(host_id: @user.id).where(is_answered: false)
    @pending_friends = Friend.where(you_id: @curr_user).where(is_accepted: false)
  end

  def edit
  @curr_user = User.find_by_id(params[:id])
  @inbox = Message.where(receiver_id: @curr_user).where(is_read: false)
  end

  def update
    @curr_user = User.find_by_id(params[:id])
    @inbox = Message.where(receiver_id: @curr_user).where(is_read: false)
    @curr_user.update(user_params)
    redirect_to user_path_url(@curr_user)
  end


  private
  def user_params
    params.require(:user).permit(:email,:name, :age, :bio, :is_hosting, :is_traveling, :gear, :image)
  end
  def user_params_create
    params.require(:user).permit(:email,:name,:password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<br>

<h1 align="center">Edit Your Profile</h1>
<br />

  <%=form_for @curr_user, :url => "/users/update/"+(@curr_user.id.to_s), :method => 'patch' do |f| %>
    <div class="container" id="newUserForm">
      <div class="form-group">
        <%= f.label :name, 'Name' %><br>
        <%= f.text_field :name, class: "form-control", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'Email' %><br>
        <%= f.text_field :email, class: "form-control", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.label :bio, 'About me' %><br>
        <%= f.text_field :bio, class: "form-control", placeholder: "Tell us about yourself", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.label :age, 'Age' %><br>
        <%= f.number_field :age, class: "form-control", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.label :image, 'Image URL here' %><br>
        <%= f.text_area :image, class: "form-control", autofocus: true, placeholder: 'upload an image onto imgur and upload here or copy a url' %>
      </div>
      <div class="form-group">
        <%= f.label :is_hosting, 'hosting campers currently?' %><br>
        <%= f.check_box :is_hosting, class: "form-control", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.label :is_traveling, 'looking for a place to camp currently?' %><br>
        <%= f.check_box :is_traveling, class: "form-control", autofocus: true %>
      </div>
      <div class="form-group">
        <%= f.label :gear, 'What gear do you have and/or need provided to you?' %><br>
        <%= f.text_field :gear, class: "form-control", autofocus: true %>
      </div>
      <div class="form-group" align= 'center' >
        <%= f.submit "Save Changes", class: 'btn btn-primary btn-sm'%>
      </div>
    </div>
  <% end %>

app/views/users/new.html.erb
<br/><br/>
<div class="background-image">
  <div class="container signup-form">
    <br/><br/><br/>
    <h1 align="center">Signup as a new user</h1>
    <%= form_for @curr_user,  :url => signup_path(@curr_user), html: {method: :post} do |f| %>
    <div class='row signup-form'>
      <div class="form-group">
        <div class="control-label col-sm-2 text-right">
          <%= f.label :email %>
        </div>
        <div class="col-xs-8">
          <%= f.text_field :email, class: "form-control", placeholder: "Enter email", autofocus: true %>
        </div>
      </div>
    </div>
    <div class='row signup-form'>
      <div class="form-group">
        <div class="control-label col-sm-2 text-right">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter name here" %>
        </div>
      </div>
    </div>
    <div class='row signup-form'>
      <div class="form-group">
        <div class="control-label col-sm-2 text-right">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>
    </div>
    <div class='row signup-form'>
      <div class="form-group">
        <div class="control-label col-sm-2 text-right">
          <%= f.label :password_confirmation, 'Confirm password' %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password again" %>
        </div>
      </div>
      <div class='row signup-form'>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10 sign-btn signup-form ">
            <%= f.submit "Sign up Here", class: 'btn btn-primary btn-lg' %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<br /><br /><br />
<div class="container">
  <h1 class="text-center">Profile Page</h1>
  <div class="row " style="background-color:#86A397;border-radius:20px">
    <div class="col-xs-4 prof-pic">
      <h1><%= @user.name%></h1>
      <%if @user.image%>
      <img class="profilePic" src="<%=@user.image%>" alt="profile pic" style ="margin:10px">
      <%else%>
      <img class="profilePic" src="http://i.imgur.com/IulSm39.jpg" alt="profile pic" style ="margin:10px">
      <%end%>
      <%if logged_in? && @user.id == current_user.id%>
          <%= link_to edit_user_path_url(@user) do %>
          <h3 class = "text-center"><span class=" glyphicon glyphicon-pencil"></span></h3>
          <%end%>
          <%= link_to my_friends_path_url(@user) do %>
          <h3><span class=" glyphicon glyphicon-user"></span><span>See my friends</span></h3>
          <%end%>
          <%if @pending_friends.present?%>
          <h4><span style="color:red"><%=@pending_friends.count%> new requests</span></h4>
          <%end%>
      <%else%>
      <%if logged_in? && @user.id != current_user.id%>
      <%= link_to new_message_path_url(:user_id => @user.id) do%>
       <h2><span class = "glyphicon glyphicon-envelope"></span></h2>
      <%end%>
      <%end%>
      <%if logged_in? && @user.id != current_user.id && @friendship.empty?%>
      <%= link_to create_friends_path_url(@user.id) , method: 'post' do%>
       <h3><span class = "glyphicon glyphicon-plus"></span><span>Add friend</span></h3>
      <%end%>
        <%end%>
      <%end%>

    </div>
    <div class="col-xs-4 prof-info">
      <%if @user.is_hosting%>
      <h2 style="color:green">Im hosting campers!</h2>
      <%else%>
      <h2 style="color:red">I cant host at the moment</h2>
      <%end%>
      <h2>Email: <%= @user.email%></h2>
      <h21Age: <%= @user.age%></h2>
      <h2>Bio: <%= @user.bio%></h2>
      <h2>Gear: <%= @user.gear%></h2>
    </div>
    <%if logged_in? && @user.id == current_user.id%>
    <div class="col-xs-4 prof-bookings text-center darkgreen" style="margin-left:-20px">
      <h2 class>My Bookings</h2><br />
      <%= button_to 'upcoming campers',answered_bookings_path_url(@user),  method: 'get', class: 'cool-btn'%><br/>
      <%= button_to 'sent requests',sent_bookings_path_url(@user), method: 'get', class: 'cool-btn expand'%><br/>
      <%= button_to 'incoming requests',incoming_bookings_path_url(@user),  method: 'get', class: 'cool-btn'%><span style="font-size:18px"><%if @incoming_pending_bookings.present?%> <span><%=@incoming_pending_bookings.count%> new requests</span><%end%><br/>

    </div>
    <%end%>
  </div>
  <%if logged_in? && @user.id == current_user.id%>
  <h1 class ="text-center"> My yards</h1>
  <%= link_to new_yard_path_url, :method=>'get' do %>
  <h3 class = "text-center">
    <span class="cart glyphicon glyphicon-plus"></span><span>Add 1</span>
  </h3>
  <%end%>
  <%else%>
  <h1 class ="text-center"><%= @user.name%>'s yards</h1>
  <%end%>
  <div class = "row">
  <% @yards.each do |yard|%>
  <div class = "col-xs-4 text-center">
  <%=link_to yard_path_url(yard) do %>
  <%if yard.image%>
  <img class="city-pic closer" src='<%=yard.image%>' alt="profile pic"  style="margin:0 !important">
  <%else%>
      <img class="city-pic closer" src="http://i.imgur.com/5gkUOut.jpg" alt="profile pic"  style="margin:0 !important">
    <%end%>
  <%end%>
  <h1><%= yard.title%></h1>
  <%if yard.kid_and_pet_friendly%>
  <h3>Kid and Pet friendly!</h3>
  <%else%>
  <h3>No pets or kids sadly</h3>
  <%end%>
  <%if yard.fire_friendly%>
  <h3>Campfires allowed!</h3>
  <%else%>
  <h3>No campfires</h3>
  <%end%>
  <h3><%= yard.city %></h3>
  <h3><%= yard.zipcode%></h3>
  <%if logged_in? && @user.id == current_user.id%>
  <%= link_to destroy_yard_path_url(yard), :method=>'delete' do %>
  <h3>
    <span class="glyphicon glyphicon-remove"></span>
  <%end%>
  <%= link_to edit_yard_path_url(yard), :method=>'get' do %>
    <span class=" glyphicon glyphicon-pencil"></span>
  </h3>
  <% end %>
  <%end%>
  <hr/>
    </div>
  <%end%>
</div>
</div>